/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2019 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include "stm32f407xx.h"     //CMSIS STM32F407xx Device Peripheral Access Layer Header File.
#include <stdlib.h>
#include <stdio.h>
#include "game_engine.h"     //Function names starting with MVB Header file


//External variables from game_engine.c
extern uint8_t frameUpdate;

extern Object_t Playermouse;
extern Object_t balloon[MVB_balloon_BUFFER_SIZE] ;
extern Object_t needle[MVB_needle_BUFFER_SIZE];

extern uint8_t currentWave;
extern uint8_t numOfballoonInWave[MVB_NUM_OF_WAVE];
extern uint8_t balloonCount;

int main (void)
{
	MVB_init();
	MVB_display_start_screen();
	//Wait in start screen until user presses shoot button
	while(SHOOT_BUTTON_READ);

	while(1){

		MVB_display_black_background();
		MVB_create_player_mouse(&Playermouse);
		MVB_draw_player_mouse(&Playermouse);

		MVB_create_balloon(balloon,numOfballoonInWave[currentWave],&Playermouse);
		MVB_draw_balloon(balloon);
		RNG_deinit();

		MVB_start_update_frame();

		while(1){
			//frameUpdate is SET every 33ms by timer6 ISR
			if(frameUpdate == SET){

				MVB_display_score();

				MVB_update_player_mouse(&Playermouse);
				MVB_draw_player_mouse(&Playermouse);

				MVB_create_needle(needle,&Playermouse);
				MVB_update_needle(needle,balloon);
				MVB_draw_needle(needle);

				MVB_update_balloon(balloon,&Playermouse);
				MVB_draw_balloon(balloon);

				//if collision detected between balloon and mouse, run game over instructions
				if(Playermouse.Object_Property.aliveFlag == MVB_ALIVE_FALSE){
					PROTOBOARD_GREEN_LED_ON;
					MVB_display_game_over_screen();
					//wait for user to press shoot button to reset game
					while(SHOOT_BUTTON_READ);
					MVB_reset_game();
					PROTOBOARD_GREEN_LED_OFF;
					break;
				}

				//if no balloons left, create more balloons
				if(balloonCount == 0){
					TIM_ctr(TIM6,STOP);
					currentWave++;
					RNG_init();
					MVB_create_balloon(balloon,numOfballoonInWave[currentWave],&Playermouse);
					TIM_ctr(TIM6,START);
				}

				frameUpdate = CLEAR;
			}
		}
	}
}

void HardFault_Handler(void)
{
	//may be turn on some LED
	while(1);
}

